### ISSUE TITLE
Do not work in browser

### ISSUE THREAD

**Issue by frusanov** [zhengpq/icon-export-for-figma#1]
Seems like plugin don't put result in clipboard
Fedora 34 (Workstation Edition)

Google Chrome: Version 94.0.4606.61 (Official Build) (64-bit) (rpm)
Mozilla Firefox: 92.0 (64-bit) (rpm)

**Comment by zhengpq** [comment]
> Seems like plugin don't put result in clipboard Fedora 34 (Workstation Edition)
> 
> Google Chrome: Version 94.0.4606.61 (Official Build) (64-bit) (rpm) Mozilla Firefox: 92.0 (64-bit) (rpm)

![image](https://user-images.githubusercontent.com/24761793/137681539-3df9e18d-cc7b-4cb5-bbe7-d58b2d78a8a7.png)


now this plugin only support the desktop app, the api does not support in the browser
